# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-04 09:23
from __future__ import unicode_literals

import Interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(Interface.models.StatusChoice('Not Started'), 'Not Started'), (Interface.models.StatusChoice('Started'), 'Started'), (Interface.models.StatusChoice('Finished'), 'Finished'), (Interface.models.StatusChoice('Error'), 'Error')], default='Not Started', max_length=5),
        ),
    ]
