# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('ST', 'Started'), ('FI', 'Finished'), ('ER', 'Error')], default='Not Started', max_length=5),
        ),
    ]
