# Generated by Django 2.1.2 on 2018-10-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0007_auto_20181004_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
