# Generated by Django 2.1.2 on 2018-10-04 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0008_workerstatus_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
