# Generated by Django 2.1.2 on 2018-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0009_workerstatus_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('UD', 'Undefined'), ('TD', 'Torrent Download'), ('TS', 'Torrent Search')], default='Undefined', max_length=5),
        ),
    ]
