# Generated by Django 2.1.2 on 2018-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0010_auto_20181005_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='message',
            field=models.CharField(choices=[('UD', 'Undefined'), ('TD', 'Torrent Download'), ('TS', 'Torrent Search')], default='Waiting', max_length=128),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
