# Generated by Django 2.1.2 on 2018-10-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0011_auto_20181008_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.CharField(default='Waiting', max_length=128),
        ),
    ]
